fix: github action

diff --git a/.github/workflows/ci-cd.yaml b/.github/workflows/ci-cd.yaml
--- a/.github/workflows/ci-cd.yaml
+++ b/.github/workflows/ci-cd.yaml
@@ -4,7 +4,7 @@
 # Proprietary and confidential
 # Written by Pipin Fitriadi <pipinfitriadi@gmail.com>, 9 December 2025
 
-name: CI / CD
+name: CI/CD
 on:
   push:
     branches: ['**']
@@ -12,10 +12,20 @@ on:
       - '[0-9]+.[0-9]+.[0-9]+'
       - '[0-9]+.[0-9]+.[0-9]+-[a-z]+'
       - '[0-9]+.[0-9]+.[0-9]+-[a-z]+.[0-9]+'
+  workflow_dispatch:
+    inputs:
+      codecoverage-percentage-passed:
+        description: Percentage as an integer for passing code coverage
+        type: number
+        default: 100
+        required: true
 jobs:
   code-quality:
     name: Code Quality
     runs-on: ubuntu-latest
+    env:
+      PIP_ROOT_USER_ACTION: ignore
+      PIP_DISABLE_PIP_VERSION_CHECK: 1
     steps:
       - name: Checkout
         uses: actions/checkout@v4
@@ -37,6 +47,9 @@ jobs:
       startsWith(github.ref, 'refs/heads/release/') ||
       startsWith(github.ref, 'refs/heads/hotfix/')
     runs-on: ubuntu-latest
+    env:
+      PIP_ROOT_USER_ACTION: ignore
+      PIP_DISABLE_PIP_VERSION_CHECK: 1
     steps:
       - name: Checkout
         uses: actions/checkout@v4
@@ -52,11 +65,16 @@ jobs:
         run: coverage run -m pytest -rfEP -q --junit-xml=code-coverage.xml
       - name: Display coverage
         run: coverage report -m
-      - name: Test coverage must be 100% passed!
-        if:
-          github.ref_type == 'tag' ||
-          contains('refs/heads/main', github.ref)
-        run: if [ $(printf '%.0f' $(coverage report | awk '$1 == "TOTAL" {print $NF+0}')) -ge 100 ]; then exit; else exit 1; fi
-  # pypi:
-  #   name: PyPI
-  #   needs: [code-quality, code-coverage]
+      - name: Upload coverage reports to Codecov
+        uses: codecov/codecov-action@v4.0.1
+        env:
+          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
+          slug: ${{ github.repository }}
+      - name: Publish coverage report
+        uses: mikepenz/action-junit-report@v4
+        if: success() || failure() # always run even if the previous step fails
+        with:
+          report_paths: code-coverage.xml
+          annotate_only: true
+      - name: Percentage passed
+        run: if [ $(printf '%.0f' $(coverage report | awk '$1 == "TOTAL" {print $NF+0}')) -ge ${{ github.event.inputs.codecoverage-percentage-passed || 100 }} ]; then exit; else exit 1; fi
